# Generated by Django 3.1.2 on 2021-01-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210130_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='webapp',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
